DOMAIN = "carpiquet_ems"
VERSION = "0.5.6-alpha-sprint5"
DEFAULT_SCAN_INTERVAL = 2

SERVICE_INSTALL_DASHBOARD = "install_dashboard"
CONF_OVERWRITE = "overwrite"
DASHBOARD_FILENAME = "carpiquet_ems.yaml"
DASHBOARD_RELATIVE_PATH = "dashboards/carpiquet_ems.yaml"

CONF_GRID_POWER_ENTITY = "grid_power_entity"
CONF_HYPER_SOC_ENTITY = "hyper_soc_entity"
CONF_HYPER_PV_ENTITY = "hyper_pv_entity"
CONF_HYPER_OUTPUT_ENTITY = "hyper_output_entity"
CONF_SOLARFLOW_SOC_ENTITY = "solarflow_soc_entity"
CONF_SOLARFLOW_PV_ENTITY = "solarflow_pv_entity"
CONF_SOLARFLOW_OUTPUT_ENTITY = "solarflow_output_entity"

CONF_HYPER_CAPACITY_ENTITY = "hyper_capacity_entity"
CONF_SOLARFLOW_CAPACITY_ENTITY = "solarflow_capacity_entity"
CONF_HYPER_MAX_POWER_ENTITY = "hyper_max_power_entity"
CONF_SOLARFLOW_MAX_POWER_ENTITY = "solarflow_max_power_entity"
CONF_HYPER_MIN_SOC_ENTITY = "hyper_min_soc_entity"
CONF_HYPER_MAX_SOC_ENTITY = "hyper_max_soc_entity"
CONF_SOLARFLOW_MIN_SOC_ENTITY = "solarflow_min_soc_entity"
CONF_SOLARFLOW_MAX_SOC_ENTITY = "solarflow_max_soc_entity"

CONF_GRID_TARGET = "grid_target"
CONF_GRID_DEADBAND = "grid_deadband"
CONF_RAMP_LIMIT_W = "ramp_limit_w"

DEFAULT_GRID_TARGET = 0.0
DEFAULT_GRID_DEADBAND = 20.0
DEFAULT_RAMP_LIMIT_W = 500.0

CONF_FALLBACK_HYPER_CAPACITY = "fallback_hyper_capacity_kwh"
CONF_FALLBACK_SOLARFLOW_CAPACITY = "fallback_solarflow_capacity_kwh"
CONF_FALLBACK_HYPER_MAX_POWER = "fallback_hyper_max_power_w"
CONF_FALLBACK_SOLARFLOW_MAX_POWER = "fallback_solarflow_max_power_w"
CONF_FALLBACK_HYPER_MIN_SOC = "fallback_hyper_min_soc"
CONF_FALLBACK_HYPER_MAX_SOC = "fallback_hyper_max_soc"
CONF_FALLBACK_SOLARFLOW_MIN_SOC = "fallback_solarflow_min_soc"
CONF_FALLBACK_SOLARFLOW_MAX_SOC = "fallback_solarflow_max_soc"

CONF_BATTERIES = "batteries"
CONF_BATTERY_SYSTEM = "system"
CONF_BATTERY_TYPE = "type"
CONF_BATTERY_SERIAL = "serial"
CONF_BATTERY_ENTITIES = "entities"

HYPER_PACK_NUM_ENTITY = "sensor.hyper_2000_pack_num"
SOLARFLOW_PACK_NUM_ENTITY = "sensor.solarflow_2400_pro_pack_num"

ATTR_GRID_POWER = "grid_power_w"
ATTR_REQUESTED_DISCHARGE = "requested_discharge_w"
ATTR_EFFECTIVE_REQUEST = "effective_request_w"
ATTR_UNSERVED_POWER = "unserved_power_w"
ATTR_HYPER_SOC = "hyper_soc_percent"
ATTR_SOLARFLOW_SOC = "solarflow_soc_percent"
ATTR_HYPER_PV = "hyper_pv_w"
ATTR_SOLARFLOW_PV = "solarflow_pv_w"
ATTR_HYPER_SIMULATED = "hyper_simulated_power_w"
ATTR_SOLARFLOW_SIMULATED = "solarflow_simulated_power_w"
ATTR_TOTAL_SIMULATED = "total_simulated_power_w"
ATTR_SIMULATED_GRID = "simulated_grid_power_w"
ATTR_BALANCE_INDEX = "balance_index_percent"
ATTR_HEALTH_SCORE = "health_score_percent"
ATTR_SYSTEM_STATUS = "system_status"
ATTR_GRID_METER_AVAILABLE = "grid_meter_available"
ATTR_HYPER_AVAILABLE = "hyper_available"
ATTR_SOLARFLOW_AVAILABLE = "solarflow_available"
ATTR_HYPER_AVAILABLE_POWER = "hyper_available_power_w"
ATTR_SOLARFLOW_AVAILABLE_POWER = "solarflow_available_power_w"
ATTR_TOTAL_AVAILABLE_POWER = "total_available_power_w"
ATTR_ACTIVE_BATTERIES = "active_batteries"
ATTR_TOTAL_BATTERIES = "total_batteries"
ATTR_TOTAL_CAPACITY = "total_capacity_kwh"
ATTR_AVERAGE_SOC = "average_soc_percent"
ATTR_DATA_MODE = "data_mode"
ATTR_FALLBACK_ACTIVE_COUNT = "fallback_active_count"
ATTR_LAST_FALLBACK_SYNC = "last_fallback_sync"
ATTR_DISPATCH_MODE = "dispatch_mode"
ATTR_LIMIT_REASON = "limit_reason"
ATTR_HYPER_CAPACITY = "hyper_capacity_kwh"
ATTR_SOLARFLOW_CAPACITY = "solarflow_capacity_kwh"
ATTR_HYPER_MAX_POWER = "hyper_max_power_w"
ATTR_SOLARFLOW_MAX_POWER = "solarflow_max_power_w"
ATTR_HYPER_MIN_SOC = "hyper_min_soc"
ATTR_HYPER_MAX_SOC = "hyper_max_soc"
ATTR_SOLARFLOW_MIN_SOC = "solarflow_min_soc"
ATTR_SOLARFLOW_MAX_SOC = "solarflow_max_soc"
ATTR_DYNAMIC_SOURCES = "dynamic_sources"
ATTR_FALLBACKS = "fallbacks"

CONF_AUTOMATION_ENABLED = "automation_enabled"
CONF_AUTOMATION_MIN_HOLD_SECONDS = "automation_min_hold_seconds"
CONF_AUTOMATION_ALLOW_FALLBACK = "automation_allow_fallback"

DEFAULT_AUTOMATION_ENABLED = True
DEFAULT_AUTOMATION_MIN_HOLD_SECONDS = 10
DEFAULT_AUTOMATION_ALLOW_FALLBACK = True

ATTR_AUTOMATION_STATE = "automation_state"
ATTR_AUTOMATION_REASON = "automation_reason"
ATTR_AUTOMATION_REQUEST_W = "automation_request_w"
ATTR_AUTOMATION_CYCLE = "automation_cycle"
ATTR_AUTOMATION_LAST_TRANSITION = "automation_last_transition"
ATTR_AUTOMATION_HOLD_REMAINING = "automation_hold_remaining_seconds"
ATTR_AUTOMATION_SAFETY_OK = "automation_safety_ok"
ATTR_AUTOMATION_POLICY = "automation_policy"
ATTR_AUTOMATION_ENABLED = "automation_enabled"

CONF_HYPER_REAL_OUTPUT_ENTITY = "hyper_real_output_entity"
CONF_SOLARFLOW_REAL_OUTPUT_ENTITY = "solarflow_real_output_entity"
ATTR_HOUSE_LOAD = "house_load_w"
ATTR_REAL_ZENDURE_TOTAL_OUTPUT = "real_zendure_total_output_w"
ATTR_REAL_HYPER_OUTPUT = "real_hyper_output_w"
ATTR_REAL_SOLARFLOW_OUTPUT = "real_solarflow_output_w"
ATTR_SIM_HYPER_HOME = "sim_hyper_home_w"
ATTR_SIM_SOLARFLOW_HOME = "sim_solarflow_home_w"
ATTR_SIM_HYPER_CHARGE = "sim_hyper_charge_w"
ATTR_SIM_SOLARFLOW_CHARGE = "sim_solarflow_charge_w"
ATTR_SIM_HYPER_EXPORT_POOL = "sim_hyper_export_pool_w"
ATTR_SIM_SOLARFLOW_EXPORT_POOL = "sim_solarflow_export_pool_w"
ATTR_SIM_CROSS_CHARGE_HYPER = "sim_cross_charge_hyper_w"
ATTR_SIM_CROSS_CHARGE_SOLARFLOW = "sim_cross_charge_solarflow_w"
ATTR_SIM_GRID_FINAL = "sim_grid_final_w"
ATTR_REAL_GRID_ERROR = "real_grid_error_w"
ATTR_SIM_GRID_ERROR = "sim_grid_error_w"
ATTR_PERFORMANCE_SCORE = "performance_score_percent"
ATTR_ZENDURE_REFERENCE_SCORE = "zendure_reference_score_percent"
ATTR_PERFORMANCE_GAIN = "performance_gain_points"
ATTR_VIRTUAL_HYPER_ENERGY = "virtual_hyper_energy_kwh"
ATTR_VIRTUAL_SOLARFLOW_ENERGY = "virtual_solarflow_energy_kwh"
ATTR_VIRTUAL_HYPER_SOC = "virtual_hyper_soc_percent"
ATTR_VIRTUAL_SOLARFLOW_SOC = "virtual_solarflow_soc_percent"
ATTR_PV_TOTAL = "pv_total_w"
ATTR_SOLAR_SURPLUS = "solar_surplus_w"
ATTR_OPERATION_MODE = "operation_mode"
ATTR_PERF_SAMPLE_COUNT = "performance_sample_count"

ATTR_SESSION_ID = "simulation_session_id"
ATTR_SESSION_ACTIVE = "simulation_session_active"
ATTR_SESSION_STARTED_AT = "simulation_session_started_at"
ATTR_SESSION_DURATION = "simulation_session_duration_seconds"
ATTR_SESSION_SAMPLE_COUNT = "simulation_session_sample_count"
ATTR_LAST_SESSION_FILE = "last_simulation_session_file"

CONF_HYPER_GRID_INPUT_ENTITY = "hyper_grid_input_entity"
CONF_SOLARFLOW_GRID_INPUT_ENTITY = "solarflow_grid_input_entity"
DEFAULT_HYPER_GRID_INPUT_ENTITY = "sensor.hyper_2000_grid_input_power"
DEFAULT_SOLARFLOW_GRID_INPUT_ENTITY = "sensor.solarflow_2400_pro_grid_input_power"

ATTR_REAL_HYPER_GRID_INPUT = "real_hyper_grid_input_w"
ATTR_REAL_SOLARFLOW_GRID_INPUT = "real_solarflow_grid_input_w"
ATTR_SELECTED_REPORT = "selected_report"
ATTR_REPORT_DOWNLOAD_URL = "report_download_url"

ATTR_PV_CURTAILED = "pv_curtailed_w"
ATTR_GRID_EXPORT_ALLOWED = "grid_export_allowed"
ATTR_GRID_EXPORT_BLOCK_REASON = "grid_export_block_reason"
ATTR_FULL_SYSTEMS_COUNT = "full_systems_count"
ATTR_HYPER_BATTERY_DISCHARGE = "hyper_battery_discharge_w"
ATTR_SOLARFLOW_BATTERY_DISCHARGE = "solarflow_battery_discharge_w"
ATTR_HYPER_PV_TO_HOME = "hyper_pv_to_home_w"
ATTR_SOLARFLOW_PV_TO_HOME = "solarflow_pv_to_home_w"

ATTR_HOUSE_LOAD_RAW = "house_load_raw_w"
ATTR_PERFORMANCE_AVERAGE = "performance_average_percent"
ATTR_ZENDURE_AVERAGE = "zendure_average_percent"
ATTR_REAL_IMPORT_ENERGY = "real_import_energy_kwh"
ATTR_REAL_EXPORT_ENERGY = "real_export_energy_kwh"
ATTR_SIM_IMPORT_ENERGY = "sim_import_energy_kwh"
ATTR_SIM_EXPORT_ENERGY = "sim_export_energy_kwh"
ATTR_PV_CHARGED_ENERGY = "pv_charged_energy_kwh"
ATTR_PV_CURTAILED_ENERGY = "pv_curtailed_energy_kwh"

ATTR_SESSION_RECORDING_STATE = "simulation_recording_state"
ATTR_SESSION_FINALIZING = "simulation_session_finalizing"
ATTR_SESSION_SAVE_ERROR = "simulation_session_save_error"
ATTR_LAST_SESSION_ENDED_AT = "last_simulation_session_ended_at"
